### ISSUE TITLE
Invalid integration key results in mapping page crashing

### ISSUE THREAD

**Issue by brianphillips** [PagerDuty/backstage-plugin-backend#68]
When trying to load the new pagerduty page with our existing software catalog, the page errors out due to the backend call returning a 404:
![image](https://github.com/PagerDuty/backstage-plugin-backend/assets/28457/a2667781-9167-4676-bd03-9ab53951e0e7)

I believe the issue is we have one (or more) backstage entities that reference a PagerDuty integration key that is invalid. On [this line of code](https://github.com/PagerDuty/backstage-plugin-backend/blob/0ab7bb3d3d957c89c4633b71cc1a4f0be8ef56bf/src/apis/pagerduty.ts#L299), the backend API endpoint returns a 404 if there are no matches for the integration key. I think might be better to handle this data quality issue more gracefully instead of throwing an exception.

**Comment by t1agob** [comment]
@brianphillips Reviewing your PR now

**Comment by t1agob** [comment]
This issue is now solved with #69 and available in **version 0.7.2**. Thanks @brianphillips for yet another contribution 🚀
