### ISSUE TITLE
Updating to Backstage v1.29.0 reports deduplicated issue

### ISSUE THREAD

**Issue by jpd4emis** [PagerDuty/backstage-plugin-backend#74]
**Describe the bug**
Updated to backstage v1.29.1 and got the warning below:

yarn backstage-cli versions:check
The following packages must be deduplicated by updating dependencies in package.json

  @backstage/backend-app-api @ ^0.7.3 should be changed to ^0.8.0

The following packages can be deduplicated by updating dependencies in package.json

  @backstage/backend-common @ ^0.22.0 should be changed to ^0.23.3
  @backstage/backend-defaults @ ^0.2.18 should be changed to ^0.4.1
  @backstage/backend-plugin-api @ ^0.6.18 should be changed to ^0.7.0
  @backstage/backend-plugin-api @ ^0.6.21 should be changed to ^0.7.0
  @backstage/plugin-permission-common @ ^0.7.14 should be changed to ^0.8.0
  @backstage/plugin-permission-node @ ^0.7.32 should be changed to ^0.8.0

**To Reproduce**
1. Update v1.28.3 to v1.29.1

**Expected behavior**
The update process to not throw any errors.

**Additional context**

**Comment by t1agob** [comment]
This is now fixed on release [0.8.1](https://www.npmjs.com/package/@pagerduty/backstage-plugin-backend/v/0.8.1). Closing the issue.
